// <auto-generated />
namespace com.cpp.calypso.web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ConsumosSinReserva_ColaboradorNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConsumosSinReserva_ColaboradorNull));
        
        string IMigrationMetadata.Id
        {
            get { return "201906191721337_ConsumosSinReserva_ColaboradorNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
