namespace com.cpp.calypso.web.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class EntidadesSincronizacion : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("SCH_PROVEEDORES.contratos_proveedores", "proveedor_id", "SCH_PROVEEDORES.proveedores");
            DropForeignKey("SCH_PROVEEDORES.contratos_proveedores", "empresa_id", "SCH_PROYECTOS.empresas");
            DropForeignKey("SCH_SERVICIOS.tipos_opciones_comidas", "contrato_id", "SCH_PROVEEDORES.contratos_proveedores");
            DropForeignKey("SCH_CATALOGOS.catalogos", "tipo_catalogo_id", "SCH_CATALOGOS.tipos_catalogos");
            DropForeignKey("SCH_SERVICIOS.consumos", "proveedor_id", "SCH_PROVEEDORES.proveedores");
            DropForeignKey("SCH_SERVICIOS.consumos_qr", "proveedor_id", "SCH_PROVEEDORES.proveedores");
            DropForeignKey("SCH_CATALOGOS.locaciones", "zona_id", "SCH_CATALOGOS.zonas");
            RenameColumn(table: "SCH_RRHH.colaboradores", name: "IsDeleted", newName: "vigente");
            AddColumn("SCH_CATALOGOS.tipos_catalogos", "m_version", c => c.Int(nullable: false));
            AddColumn("SCH_CATALOGOS.tipos_catalogos", "m_ref", c => c.String());
            AddColumn("SCH_PROVEEDORES.proveedores", "m_version", c => c.Int(nullable: false));
            AddColumn("SCH_PROVEEDORES.proveedores", "m_ref", c => c.String());
            AddColumn("SCH_PROVEEDORES.contratos_proveedores", "m_version", c => c.Int(nullable: false));
            AddColumn("SCH_PROVEEDORES.contratos_proveedores", "m_ref", c => c.String());
            AddColumn("SCH_PROYECTOS.empresas", "m_version", c => c.Int(nullable: false));
            AddColumn("SCH_PROYECTOS.empresas", "m_ref", c => c.String());
            AddColumn("SCH_SERVICIOS.tipos_opciones_comidas", "m_version", c => c.Int(nullable: false));
            AddColumn("SCH_SERVICIOS.tipos_opciones_comidas", "m_ref", c => c.String());
            AddColumn("SCH_CATALOGOS.catalogos", "m_version", c => c.Int(nullable: false));
            AddColumn("SCH_CATALOGOS.catalogos", "m_ref", c => c.String());
            AddColumn("SCH_RRHH.colaboradores", "m_version", c => c.Int(nullable: false));
            AddColumn("SCH_RRHH.colaboradores", "m_ref", c => c.String());
            AddColumn("SCH_SERVICIOS.consumos", "m_version", c => c.Int(nullable: false));
            AddColumn("SCH_SERVICIOS.consumos", "m_ref", c => c.String());
            AddColumn("SCH_SERVICIOS.consumos_qr", "usuario_generador_id", c => c.Int(nullable: false));
            AddColumn("SCH_SERVICIOS.consumos_qr", "m_version", c => c.Int(nullable: false));
            AddColumn("SCH_SERVICIOS.consumos_qr", "m_ref", c => c.String());
            AddColumn("SCH_SERVICIOS.consumos_viandas", "m_version", c => c.Int(nullable: false));
            AddColumn("SCH_SERVICIOS.consumos_viandas", "m_ref", c => c.String());
            AddColumn("SCH_SERVICIOS.solicitudes_viandas", "m_version", c => c.Int(nullable: false));
            AddColumn("SCH_SERVICIOS.solicitudes_viandas", "m_ref", c => c.String());
            AddColumn("SCH_CATALOGOS.locaciones", "m_version", c => c.Int(nullable: false));
            AddColumn("SCH_CATALOGOS.locaciones", "m_ref", c => c.String());
            AddColumn("SCH_CATALOGOS.zonas", "m_version", c => c.Int(nullable: false));
            AddColumn("SCH_CATALOGOS.zonas", "m_ref", c => c.String());
            AddColumn("SCH_SERVICIOS.consumos_viandas_qr", "m_version", c => c.Int(nullable: false));
            AddColumn("SCH_SERVICIOS.consumos_viandas_qr", "m_ref", c => c.String());
            AlterColumn("SCH_CATALOGOS.tipos_catalogos", "nombre", c => c.String());
            AlterColumn("SCH_CATALOGOS.tipos_catalogos", "codigo", c => c.String());
            AlterColumn("SCH_CATALOGOS.tipos_catalogos", "tipo_ordenamiento", c => c.String());
            AlterColumn("SCH_PROVEEDORES.proveedores", "identificacion", c => c.String());
            AlterColumn("SCH_PROVEEDORES.proveedores", "razon_social", c => c.String());
            AlterColumn("SCH_PROVEEDORES.proveedores", "coordenadas", c => c.String());
            AlterColumn("SCH_PROVEEDORES.proveedores", "codigo_sap", c => c.String());
            AlterColumn("SCH_PROVEEDORES.proveedores", "usuario", c => c.String());
            AlterColumn("SCH_PROVEEDORES.contratos_proveedores", "codigo", c => c.String());
            AlterColumn("SCH_PROVEEDORES.contratos_proveedores", "objeto", c => c.String());
            AlterColumn("SCH_PROVEEDORES.contratos_proveedores", "orden_compra", c => c.String());
            AlterColumn("SCH_PROYECTOS.empresas", "identificacion", c => c.String());
            AlterColumn("SCH_PROYECTOS.empresas", "razon_social", c => c.String());
            AlterColumn("SCH_PROYECTOS.empresas", "direccion", c => c.String());
            AlterColumn("SCH_PROYECTOS.empresas", "correo", c => c.String());
            AlterColumn("SCH_PROYECTOS.empresas", "telefono", c => c.String());
            AlterColumn("SCH_PROYECTOS.empresas", "observaciones", c => c.String());
            AlterColumn("SCH_PROYECTOS.empresas", "codigo_sap", c => c.String());
            AlterColumn("SCH_RRHH.colaboradores", "catalogo_sitio_trabajo_id", c => c.Int(nullable: false));
            AlterColumn("SCH_RRHH.colaboradores", "numero_identificacion", c => c.String());
            AlterColumn("SCH_RRHH.colaboradores", "catalogo_codigo_incapacidad_id", c => c.Int(nullable: false));
            AlterColumn("SCH_SERVICIOS.consumos", "observacion", c => c.String());
            AlterColumn("SCH_SERVICIOS.consumos_qr", "cedula", c => c.String());
            AlterColumn("SCH_SERVICIOS.consumos_viandas", "observaciones", c => c.String());
            AlterColumn("SCH_SERVICIOS.solicitudes_viandas", "referencia_ubicacion", c => c.String());
            AlterColumn("SCH_SERVICIOS.solicitudes_viandas", "observaciones", c => c.String());
            AlterColumn("SCH_CATALOGOS.locaciones", "nombre", c => c.String());
            AlterColumn("SCH_CATALOGOS.zonas", "codigo", c => c.String());
            AlterColumn("SCH_CATALOGOS.zonas", "nombre", c => c.String());
            AlterColumn("SCH_CATALOGOS.zonas", "Descripcion", c => c.String());
            AlterColumn("SCH_SERVICIOS.consumos_viandas_qr", "identificacion", c => c.String());
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_tipo_identificacion_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_genero_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_etnia_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_estado_civil_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_codigo_siniestro_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_formacion_educativa_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_grupo_personal_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_destino_estancia_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_sitio_trabajo_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_area_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_cargo_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_vinculo_laboral_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_clase_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_plan_beneficios_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_plan_salud_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_cobertura_dependiente_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_planes_beneficios_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_asociacion_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_apto_medico_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_division_personal_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_subdivision_personal_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_tipo_contrato_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_clase_contrato_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_funcion_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_tipo_nomina_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_periodo_nomina_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_forma_pago_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_grupo_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_subgrupo_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_banco_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_tipo_cuenta_id");
            CreateIndex("SCH_RRHH.colaboradores", "empresa_id");
            CreateIndex("SCH_RRHH.colaboradores", "locacion_trabajo_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_encuadre_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_encargado_personal_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_codigo_incapacidad_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_sector_id");
            CreateIndex("SCH_RRHH.colaboradores", "catalogo_via_pago_id");
            CreateIndex("SCH_SERVICIOS.solicitudes_viandas", "solicitud_original_id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_apto_medico_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_area_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_asociacion_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_banco_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_cargo_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_clase_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_clase_contrato_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_cobertura_dependiente_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_codigo_incapacidad_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_codigo_siniestro_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_destino_estancia_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_division_personal_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_encargado_personal_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_encuadre_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_estado_civil_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_etnia_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_formacion_educativa_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_forma_pago_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_funcion_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_genero_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_grupo_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_grupo_personal_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_periodo_nomina_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_plan_beneficios_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_planes_beneficios_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_plan_salud_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_sector_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_sitio_trabajo_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_subdivision_personal_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_subgrupo_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_tipo_contrato_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_tipo_cuenta_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_tipo_identificacion_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_tipo_nomina_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_via_pago_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "catalogo_vinculo_laboral_id", "SCH_CATALOGOS.catalogos", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "empresa_id", "SCH_PROYECTOS.empresas", "id");
            AddForeignKey("SCH_RRHH.colaboradores", "locacion_trabajo_id", "SCH_CATALOGOS.locaciones", "id", cascadeDelete: true);
            AddForeignKey("SCH_SERVICIOS.solicitudes_viandas", "solicitud_original_id", "SCH_SERVICIOS.solicitudes_viandas", "id");
            AddForeignKey("SCH_PROVEEDORES.contratos_proveedores", "proveedor_id", "SCH_PROVEEDORES.proveedores", "id");
            AddForeignKey("SCH_PROVEEDORES.contratos_proveedores", "empresa_id", "SCH_PROYECTOS.empresas", "id");
            AddForeignKey("SCH_SERVICIOS.tipos_opciones_comidas", "contrato_id", "SCH_PROVEEDORES.contratos_proveedores", "id");
            AddForeignKey("SCH_CATALOGOS.catalogos", "tipo_catalogo_id", "SCH_CATALOGOS.tipos_catalogos", "id");
            AddForeignKey("SCH_SERVICIOS.consumos", "proveedor_id", "SCH_PROVEEDORES.proveedores", "id");
            AddForeignKey("SCH_SERVICIOS.consumos_qr", "proveedor_id", "SCH_PROVEEDORES.proveedores", "id");
            AddForeignKey("SCH_CATALOGOS.locaciones", "zona_id", "SCH_CATALOGOS.zonas", "id");
            DropColumn("SCH_PROYECTOS.empresas", "vigente1");
            DropColumn("SCH_SERVICIOS.consumos_qr", "usuario_generador");
            DropColumn("SCH_SERVICIOS.solicitudes_viandas", "LastModificationTime");
            DropColumn("SCH_SERVICIOS.solicitudes_viandas", "LastModifierUserId");
            DropColumn("SCH_SERVICIOS.solicitudes_viandas", "CreationTime");
            DropColumn("SCH_SERVICIOS.solicitudes_viandas", "CreatorUserId");
        }
        
        public override void Down()
        {
            AddColumn("SCH_SERVICIOS.solicitudes_viandas", "CreatorUserId", c => c.Long());
            AddColumn("SCH_SERVICIOS.solicitudes_viandas", "CreationTime", c => c.DateTime(nullable: false));
            AddColumn("SCH_SERVICIOS.solicitudes_viandas", "LastModifierUserId", c => c.Long());
            AddColumn("SCH_SERVICIOS.solicitudes_viandas", "LastModificationTime", c => c.DateTime());
            AddColumn("SCH_SERVICIOS.consumos_qr", "usuario_generador", c => c.Int(nullable: false));
            AddColumn("SCH_PROYECTOS.empresas", "vigente1", c => c.Boolean(nullable: false));
            DropForeignKey("SCH_CATALOGOS.locaciones", "zona_id", "SCH_CATALOGOS.zonas");
            DropForeignKey("SCH_SERVICIOS.consumos_qr", "proveedor_id", "SCH_PROVEEDORES.proveedores");
            DropForeignKey("SCH_SERVICIOS.consumos", "proveedor_id", "SCH_PROVEEDORES.proveedores");
            DropForeignKey("SCH_CATALOGOS.catalogos", "tipo_catalogo_id", "SCH_CATALOGOS.tipos_catalogos");
            DropForeignKey("SCH_SERVICIOS.tipos_opciones_comidas", "contrato_id", "SCH_PROVEEDORES.contratos_proveedores");
            DropForeignKey("SCH_PROVEEDORES.contratos_proveedores", "empresa_id", "SCH_PROYECTOS.empresas");
            DropForeignKey("SCH_PROVEEDORES.contratos_proveedores", "proveedor_id", "SCH_PROVEEDORES.proveedores");
            DropForeignKey("SCH_SERVICIOS.solicitudes_viandas", "solicitud_original_id", "SCH_SERVICIOS.solicitudes_viandas");
            DropForeignKey("SCH_RRHH.colaboradores", "locacion_trabajo_id", "SCH_CATALOGOS.locaciones");
            DropForeignKey("SCH_RRHH.colaboradores", "empresa_id", "SCH_PROYECTOS.empresas");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_vinculo_laboral_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_via_pago_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_tipo_nomina_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_tipo_identificacion_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_tipo_cuenta_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_tipo_contrato_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_subgrupo_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_subdivision_personal_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_sitio_trabajo_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_sector_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_plan_salud_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_planes_beneficios_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_plan_beneficios_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_periodo_nomina_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_grupo_personal_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_grupo_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_genero_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_funcion_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_forma_pago_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_formacion_educativa_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_etnia_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_estado_civil_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_encuadre_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_encargado_personal_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_division_personal_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_destino_estancia_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_codigo_siniestro_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_codigo_incapacidad_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_cobertura_dependiente_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_clase_contrato_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_clase_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_cargo_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_banco_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_asociacion_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_area_id", "SCH_CATALOGOS.catalogos");
            DropForeignKey("SCH_RRHH.colaboradores", "catalogo_apto_medico_id", "SCH_CATALOGOS.catalogos");
            DropIndex("SCH_SERVICIOS.solicitudes_viandas", new[] { "solicitud_original_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_via_pago_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_sector_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_codigo_incapacidad_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_encargado_personal_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_encuadre_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "locacion_trabajo_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "empresa_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_tipo_cuenta_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_banco_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_subgrupo_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_grupo_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_forma_pago_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_periodo_nomina_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_tipo_nomina_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_funcion_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_clase_contrato_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_tipo_contrato_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_subdivision_personal_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_division_personal_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_apto_medico_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_asociacion_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_planes_beneficios_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_cobertura_dependiente_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_plan_salud_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_plan_beneficios_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_clase_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_vinculo_laboral_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_cargo_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_area_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_sitio_trabajo_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_destino_estancia_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_grupo_personal_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_formacion_educativa_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_codigo_siniestro_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_estado_civil_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_etnia_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_genero_id" });
            DropIndex("SCH_RRHH.colaboradores", new[] { "catalogo_tipo_identificacion_id" });
            AlterColumn("SCH_SERVICIOS.consumos_viandas_qr", "identificacion", c => c.String(nullable: false, maxLength: 15));
            AlterColumn("SCH_CATALOGOS.zonas", "Descripcion", c => c.String(nullable: false, maxLength: 400));
            AlterColumn("SCH_CATALOGOS.zonas", "nombre", c => c.String(nullable: false, maxLength: 60));
            AlterColumn("SCH_CATALOGOS.zonas", "codigo", c => c.String(nullable: false, maxLength: 10));
            AlterColumn("SCH_CATALOGOS.locaciones", "nombre", c => c.String(nullable: false, maxLength: 200));
            AlterColumn("SCH_SERVICIOS.solicitudes_viandas", "observaciones", c => c.String(maxLength: 255));
            AlterColumn("SCH_SERVICIOS.solicitudes_viandas", "referencia_ubicacion", c => c.String(maxLength: 200));
            AlterColumn("SCH_SERVICIOS.consumos_viandas", "observaciones", c => c.String(nullable: false, maxLength: 500));
            AlterColumn("SCH_SERVICIOS.consumos_qr", "cedula", c => c.String(nullable: false, maxLength: 15));
            AlterColumn("SCH_SERVICIOS.consumos", "observacion", c => c.String(nullable: false, maxLength: 500));
            AlterColumn("SCH_RRHH.colaboradores", "catalogo_codigo_incapacidad_id", c => c.Int());
            AlterColumn("SCH_RRHH.colaboradores", "numero_identificacion", c => c.String(maxLength: 25));
            AlterColumn("SCH_RRHH.colaboradores", "catalogo_sitio_trabajo_id", c => c.String());
            AlterColumn("SCH_PROYECTOS.empresas", "codigo_sap", c => c.String(maxLength: 200));
            AlterColumn("SCH_PROYECTOS.empresas", "observaciones", c => c.String(maxLength: 800));
            AlterColumn("SCH_PROYECTOS.empresas", "telefono", c => c.String(nullable: false, maxLength: 15));
            AlterColumn("SCH_PROYECTOS.empresas", "correo", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("SCH_PROYECTOS.empresas", "direccion", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("SCH_PROYECTOS.empresas", "razon_social", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("SCH_PROYECTOS.empresas", "identificacion", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("SCH_PROVEEDORES.contratos_proveedores", "orden_compra", c => c.String(nullable: false, maxLength: 10));
            AlterColumn("SCH_PROVEEDORES.contratos_proveedores", "objeto", c => c.String(nullable: false, maxLength: 500));
            AlterColumn("SCH_PROVEEDORES.contratos_proveedores", "codigo", c => c.String(nullable: false, maxLength: 30));
            AlterColumn("SCH_PROVEEDORES.proveedores", "usuario", c => c.String(maxLength: 60));
            AlterColumn("SCH_PROVEEDORES.proveedores", "codigo_sap", c => c.String(maxLength: 30));
            AlterColumn("SCH_PROVEEDORES.proveedores", "coordenadas", c => c.String(maxLength: 50));
            AlterColumn("SCH_PROVEEDORES.proveedores", "razon_social", c => c.String(nullable: false, maxLength: 100));
            AlterColumn("SCH_PROVEEDORES.proveedores", "identificacion", c => c.String(nullable: false, maxLength: 20));
            AlterColumn("SCH_CATALOGOS.tipos_catalogos", "tipo_ordenamiento", c => c.String(nullable: false, maxLength: 3));
            AlterColumn("SCH_CATALOGOS.tipos_catalogos", "codigo", c => c.String(nullable: false, maxLength: 50));
            AlterColumn("SCH_CATALOGOS.tipos_catalogos", "nombre", c => c.String(nullable: false, maxLength: 200));
            DropColumn("SCH_SERVICIOS.consumos_viandas_qr", "m_ref");
            DropColumn("SCH_SERVICIOS.consumos_viandas_qr", "m_version");
            DropColumn("SCH_CATALOGOS.zonas", "m_ref");
            DropColumn("SCH_CATALOGOS.zonas", "m_version");
            DropColumn("SCH_CATALOGOS.locaciones", "m_ref");
            DropColumn("SCH_CATALOGOS.locaciones", "m_version");
            DropColumn("SCH_SERVICIOS.solicitudes_viandas", "m_ref");
            DropColumn("SCH_SERVICIOS.solicitudes_viandas", "m_version");
            DropColumn("SCH_SERVICIOS.consumos_viandas", "m_ref");
            DropColumn("SCH_SERVICIOS.consumos_viandas", "m_version");
            DropColumn("SCH_SERVICIOS.consumos_qr", "m_ref");
            DropColumn("SCH_SERVICIOS.consumos_qr", "m_version");
            DropColumn("SCH_SERVICIOS.consumos_qr", "usuario_generador_id");
            DropColumn("SCH_SERVICIOS.consumos", "m_ref");
            DropColumn("SCH_SERVICIOS.consumos", "m_version");
            DropColumn("SCH_RRHH.colaboradores", "m_ref");
            DropColumn("SCH_RRHH.colaboradores", "m_version");
            DropColumn("SCH_CATALOGOS.catalogos", "m_ref");
            DropColumn("SCH_CATALOGOS.catalogos", "m_version");
            DropColumn("SCH_SERVICIOS.tipos_opciones_comidas", "m_ref");
            DropColumn("SCH_SERVICIOS.tipos_opciones_comidas", "m_version");
            DropColumn("SCH_PROYECTOS.empresas", "m_ref");
            DropColumn("SCH_PROYECTOS.empresas", "m_version");
            DropColumn("SCH_PROVEEDORES.contratos_proveedores", "m_ref");
            DropColumn("SCH_PROVEEDORES.contratos_proveedores", "m_version");
            DropColumn("SCH_PROVEEDORES.proveedores", "m_ref");
            DropColumn("SCH_PROVEEDORES.proveedores", "m_version");
            DropColumn("SCH_CATALOGOS.tipos_catalogos", "m_ref");
            DropColumn("SCH_CATALOGOS.tipos_catalogos", "m_version");
            RenameColumn(table: "SCH_RRHH.colaboradores", name: "vigente", newName: "IsDeleted");
            AddForeignKey("SCH_CATALOGOS.locaciones", "zona_id", "SCH_CATALOGOS.zonas", "Id", cascadeDelete: true);
            AddForeignKey("SCH_SERVICIOS.consumos_qr", "proveedor_id", "SCH_PROVEEDORES.proveedores", "Id", cascadeDelete: true);
            AddForeignKey("SCH_SERVICIOS.consumos", "proveedor_id", "SCH_PROVEEDORES.proveedores", "Id", cascadeDelete: true);
            AddForeignKey("SCH_CATALOGOS.catalogos", "tipo_catalogo_id", "SCH_CATALOGOS.tipos_catalogos", "Id", cascadeDelete: true);
            AddForeignKey("SCH_SERVICIOS.tipos_opciones_comidas", "contrato_id", "SCH_PROVEEDORES.contratos_proveedores", "Id", cascadeDelete: true);
            AddForeignKey("SCH_PROVEEDORES.contratos_proveedores", "empresa_id", "SCH_PROYECTOS.empresas", "Id", cascadeDelete: true);
            AddForeignKey("SCH_PROVEEDORES.contratos_proveedores", "proveedor_id", "SCH_PROVEEDORES.proveedores", "Id", cascadeDelete: true);
        }
    }
}
